{-# LANGUAGE    DeriveGeneric              #-}
{-# LANGUAGE    StandaloneDeriving         #-}
{-# OPTIONS_GHC -fno-warn-orphans  #-}
module JavaATerms where

import ATerm.Generics
import GHC.Generics
import Language.Java.Syntax

deriving instance Generic CompilationUnit
deriving instance Generic PackageDecl
deriving instance Generic ImportDecl
deriving instance Generic TypeDecl
deriving instance Generic ClassDecl
deriving instance Generic ClassBody
deriving instance Generic EnumBody
deriving instance Generic EnumConstant
deriving instance Generic InterfaceDecl
deriving instance Generic InterfaceBody
deriving instance Generic Decl
deriving instance Generic MemberDecl
deriving instance Generic VarDecl
deriving instance Generic VarDeclId
deriving instance Generic VarInit
deriving instance Generic FormalParam
deriving instance Generic MethodBody
deriving instance Generic ConstructorBody
deriving instance Generic ExplConstrInv
deriving instance Generic Modifier
deriving instance Generic Annotation
deriving instance Generic ElementValue
deriving instance Generic Block
deriving instance Generic BlockStmt
deriving instance Generic Stmt
deriving instance Generic Catch
deriving instance Generic SwitchBlock
deriving instance Generic SwitchLabel
deriving instance Generic ForInit
deriving instance Generic Exp
deriving instance Generic Literal
deriving instance Generic Op
deriving instance Generic AssignOp
deriving instance Generic Lhs
deriving instance Generic ArrayIndex
deriving instance Generic FieldAccess
deriving instance Generic MethodInvocation
deriving instance Generic ArrayInit
deriving instance Generic Type
deriving instance Generic RefType
deriving instance Generic ClassType
deriving instance Generic TypeArgument
deriving instance Generic WildcardBound
deriving instance Generic PrimType
deriving instance Generic TypeParam
deriving instance Generic Ident
deriving instance Generic Name

instance ToATerm CompilationUnit where
instance ToATerm PackageDecl where
instance ToATerm ImportDecl where
instance ToATerm TypeDecl where
instance ToATerm ClassDecl where
instance ToATerm ClassBody where
instance ToATerm EnumBody where
instance ToATerm EnumConstant where
instance ToATerm InterfaceDecl where
instance ToATerm InterfaceBody where
instance ToATerm Decl where
instance ToATerm MemberDecl where
instance ToATerm VarDecl where
instance ToATerm VarDeclId where
instance ToATerm VarInit where
instance ToATerm FormalParam where
instance ToATerm MethodBody where
instance ToATerm ConstructorBody where
instance ToATerm ExplConstrInv where
instance ToATerm Modifier where
instance ToATerm Annotation where
instance ToATerm ElementValue where
instance ToATerm Block where
instance ToATerm BlockStmt where
instance ToATerm Stmt where
instance ToATerm Catch where
instance ToATerm SwitchBlock where
instance ToATerm SwitchLabel where
instance ToATerm ForInit where
instance ToATerm Exp where
instance ToATerm Literal where
instance ToATerm Op where
instance ToATerm AssignOp where
instance ToATerm Lhs where
instance ToATerm ArrayIndex where
instance ToATerm FieldAccess where
instance ToATerm MethodInvocation where
instance ToATerm ArrayInit where
instance ToATerm Type where
instance ToATerm RefType where
instance ToATerm ClassType where
instance ToATerm TypeArgument where
instance ToATerm WildcardBound where
instance ToATerm PrimType where
instance ToATerm TypeParam where
instance ToATerm Ident where
instance ToATerm Name where

instance FromATerm CompilationUnit where
instance FromATerm PackageDecl where
instance FromATerm ImportDecl where
instance FromATerm TypeDecl where
instance FromATerm ClassDecl where
instance FromATerm ClassBody where
instance FromATerm EnumBody where
instance FromATerm EnumConstant where
instance FromATerm InterfaceDecl where
instance FromATerm InterfaceBody where
instance FromATerm Decl where
instance FromATerm MemberDecl where
instance FromATerm VarDecl where
instance FromATerm VarDeclId where
instance FromATerm VarInit where
instance FromATerm FormalParam where
instance FromATerm MethodBody where
instance FromATerm ConstructorBody where
instance FromATerm ExplConstrInv where
instance FromATerm Modifier where
instance FromATerm Annotation where
instance FromATerm ElementValue where
instance FromATerm Block where
instance FromATerm BlockStmt where
instance FromATerm Stmt where
instance FromATerm Catch where
instance FromATerm SwitchBlock where
instance FromATerm SwitchLabel where
instance FromATerm ForInit where
instance FromATerm Exp where
instance FromATerm Literal where
instance FromATerm Op where
instance FromATerm AssignOp where
instance FromATerm Lhs where
instance FromATerm ArrayIndex where
instance FromATerm FieldAccess where
instance FromATerm MethodInvocation where
instance FromATerm ArrayInit where
instance FromATerm Type where
instance FromATerm RefType where
instance FromATerm ClassType where
instance FromATerm TypeArgument where
instance FromATerm WildcardBound where
instance FromATerm PrimType where
instance FromATerm TypeParam where
instance FromATerm Ident where
instance FromATerm Name where
